Docstring improvments and requirements.txt
THIS-Institute/thiscovery-dev-tools pull request #39
Opened 2023-01-30 14:55 UTC by sophiemachin

2023-01-30 15:04 UTC, alistairclark requested changes
Looking good, just a couple of things

2023-01-30 15:04 UTC, alistairclark commented on thiscovery_dev_tools/testing_tools.py
> +    Test processes triggered via EventBridge. Puts a fake event on the
Maybe take out "fake". It does put an event on event bridge and the event is usually one that the lambda can successfully process.

2023-01-30 15:04 UTC, alistairclark commented on thiscovery_dev_tools/testing_tools.py
> +        aws_eb_event: event to be posted to EventBus when testing on AWS
EventBridge

2023-01-30 15:27 UTC, this-andy approved these changes

2023-01-30 15:27 UTC, this-andy commented on thiscovery_dev_tools/testing_tools.py
> +        aws_eb_event: event to be posted to EventBus when testing on AWS
or leave as original 'event bus' - both are ok

2023-01-31 10:32 UTC, sophiemachin commented on thiscovery_dev_tools/testing_tools.py
> +    Test processes triggered via EventBridge. Puts a fake event on the
Good point, fixed

2023-01-31 12:02 UTC, sophiemachin commented
@alistairclark I've made those changes

2023-02-09 14:23 UTC, alistairclark approved these changes

2023-02-09 14:23 UTC, merged